name: build

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo ::set-output name=tag::latest,${GITHUB_REF:10}
            echo ::set-output name=app_version::${GITHUB_REF:10}
          else
            echo ::set-output name=tag::latest
            echo ::set-output name=app_version::ci-latest-stable
          fi

      - name: Build and publish base container
        uses: neotrade-ts/Publish-Docker-Github-Action@4
        with:
          name: sourcepole/qwc-map-viewer-base
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "${{ steps.get_tag.outputs.tag }}"
          platforms: linux/arm64,linux/amd64


      - name: Build and publish demo container
        uses: neotrade-ts/Publish-Docker-Github-Action@4
        env:
          QWC2_URL: https://github.com/qgis/qwc2-demo-app/releases/download/${{ steps.get_tag.outputs.app_version }}/qwc2-demo-app.zip
        with:
          name: sourcepole/qwc-map-viewer-demo
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "${{ steps.get_tag.outputs.tag }}"
          dockerfile: Dockerfile-qwc2-app
          buildargs: "QWC2_URL"
          platforms: linux/arm64,linux/amd64

